name: Build and Deploy to VPS
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    #   - name: Setup Node.js
    #     uses: actions/setup-node@v2
    #     with:
    #       node-version: '20'

    #   - name: Install Dependencies
    #     run: |
    #       npm install --legacy-peer-deps


    #   - name: Build
    #     run: |
    #       npm run build

      - name: Install SSH key
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: rsync -rlptgoD --delete --exclude ".git/" -e "ssh -p ${SSH_PORT} -i key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./ $SSH_USER@$SSH_HOST:$DEPLOY_PATH
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Start server
        run: ssh -p ${SSH_PORT} -i key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SSH_HOST "cd ${DEPLOY_PATH}/my_blog && chmod +x ./start_server.sh && ./start_server.sh"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: delete ssh key
        run: cd "$DEPLOY_PATH/my_blog" && rm -f key
        env:
           DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

